use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use anyhow::{anyhow, bail};
use log::{info, warn};

use crate::config::Config;
use crate::constants::CONFIG_FILE_NAME;
use crate::error::Result;
use crate::merge_tree::{MergeOption, MergeTree};
use crate::symlink::{Symlink, SymlinkMode};

use super::install;
use super::resolve_track_file;

/// 反向接管：将已有配置目录移入 stow 仓库并创建链接。
///
/// 每个 source 目录以其 basename 作为 pack 名，在 `stow_dir` 下创建 pack 目录，
/// 自动生成 `stow-cm.toml`（target = source），然后移入文件并安装链接。
pub fn adopt(global: &Config, sources: &[PathBuf], stow_dir: impl AsRef<Path>) -> Result<()> {
    let stow_dir = stow_dir.as_ref();

    for source in sources {
        let pack_name = source
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| anyhow!("{}: cannot determine pack name", source.display()))?;

        let pack_dir = stow_dir.join(pack_name);
        info!(
            "adopt {pack_name}: source={} pack={}",
            source.display(),
            pack_dir.display()
        );

        let config_path = pack_dir.join(CONFIG_FILE_NAME);

        // 检查 pack 目录：已存在、非空、且无 stow-cm.toml → 拒绝
        if pack_dir.exists() && !config_path.exists() {
            let mut entries = std::fs::read_dir(&pack_dir)?;
            if entries.next().is_some() {
                bail!(
                    "{pack_name}: pack directory '{}' already exists with content \
                     but no {CONFIG_FILE_NAME} — refusing to adopt.\n\
                     Remove the directory or create a {CONFIG_FILE_NAME} first.",
                    pack_dir.display()
                );
            }
        }

        // 确保 pack 目录存在
        std::fs::create_dir_all(&pack_dir)?;

        // 如果没有 stow-cm.toml，先生成配置（含 target），再加载
        if !config_path.exists() {
            generate_config(&config_path, pack_name, source)?;
            info!("{pack_name}: generated stow-cm.toml");
        }

        let config = Config::for_pack(&pack_dir, global, None, false)?;
        let target = config
            .target
            .as_ref()
            .ok_or_else(|| anyhow!("{pack_name}: target is not configured"))?;
        let tc = std::fs::canonicalize(target);
        let sc = std::fs::canonicalize(source);
        let target_matches = match (tc, sc) {
            (Ok(tc), Ok(sc)) => tc == sc,
            _ => false,
        };
        if !target_matches {
            bail!(
                "{pack_name}: target in stow-cm.toml does not match source '{}'",
                source.display()
            );
        }

        // 已安装的 pack 不能再次 adopt
        let track_file = resolve_track_file(&pack_dir, pack_name)?;
        if track_file.try_exists()? {
            bail!("{pack_name}: pack has been installed, cannot adopt");
        }

        let ignore_re = config.ignore_regex()?;

        // 用 merge_tree 扫描 source 目录，检测与 pack 的冲突，同时获取需移动的文件列表
        // 注意：adopt 场景不允许 override 自动跳过冲突，over 传 None
        let merge_option = Arc::new(MergeOption {
            ignore: ignore_re,
            over: None,
            fold: Some(true),
            symlink_mode: Some(SymlinkMode::Symlink),
        });
        let merge_result = MergeTree::new(&pack_dir, target, Some(merge_option)).merge_add()?;

        if let Some(ref conflicts) = merge_result.conflicts {
            warn!("{pack_name}: {} conflict(s) detected:", conflicts.len());
            for conflict in conflicts {
                warn!("  - {}", conflict.display());
            }
            bail!(
                "{pack_name}: adopt aborted due to conflicts.
                 Resolve conflicts manually or add override patterns in stow-cm.toml."
            );
        }

        // 将 merge_tree 返回的源文件移入 pack
        if let Some(ref to_create) = merge_result.to_create_symlinks {
            adopt_move_files(pack_name, to_create)?;
        }

        // 复用 install 创建链接 + 写 track file + 执行 init 脚本
        let config = Arc::new(config);
        install::install(&config, &pack_dir)?;
    }

    Ok(())
}

/// 为新 pack 生成最小 `stow-cm.toml`。
/// `target` 不显式写出，由全局配置默认值继承；
/// 注释记录源目录路径，供 `for_pack` 比对校验。
fn generate_config(config_path: &Path, pack_name: &str, source: &Path) -> Result<()> {
    let content = format!(
        "# Auto-generated by stow-cm adopt\n\
         name = \"{pack_name}\"\n\
         # target inherits from global config (default: ${{XDG_CONFIG_HOME:-~/.config}}/${{PACK_NAME}}/);\n\
         # for this pack it resolves to: \"{}\"\n",
        source.display()
    );

    std::fs::write(config_path, content).map_err(|e| {
        anyhow!(
            "{pack_name}: failed to write {}: {e}",
            config_path.display()
        )
    })?;
    Ok(())
}

/// 将 `merge_tree` 扫描结果中的文件从 source 移入 pack。
///
/// 每个 Symlink 的 `src` 是 source 目录中的路径，`dst` 是 pack 目录中的对应位置。
/// 合并后由 install 阶段在 `dst` 位置创建指向 pack 中文件的 symlink。
fn adopt_move_files(pack_name: &str, to_move: &[Symlink]) -> Result<()> {
    for symlink in to_move {
        let src = &symlink.src;
        let dst = &symlink.dst;

        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent)?;
        }

        info!("{pack_name}: adopt {}", src.display());
        if std::fs::rename(src, dst).is_err() && rename_cross_fs(src, dst).is_err() {
            bail!("{pack_name}: failed to adopt {}", src.display());
        }
    }

    Ok(())
}

/// 跨文件系统移动：先递归复制到目标，再删除源文件。
/// 显式处理 symlink 以避免 `is_dir()` 跟随解引用、`remove_dir()` 在 symlink 上失败。
fn rename_cross_fs(src: &Path, dst: &Path) -> Result<(), std::io::Error> {
    let meta = src.symlink_metadata()?;
    if meta.file_type().is_symlink() {
        if src.is_dir() {
            std::fs::create_dir_all(dst)?;
            for entry in std::fs::read_dir(src)? {
                let entry = entry?;
                let src_child = entry.path();
                let dst_child = dst.join(entry.file_name());
                rename_cross_fs(&src_child, &dst_child)?;
            }
        } else {
            std::fs::copy(src, dst)?;
        }
        std::fs::remove_file(src)?;
    } else if meta.file_type().is_dir() {
        std::fs::create_dir_all(dst)?;
        for entry in std::fs::read_dir(src)? {
            let entry = entry?;
            let src_child = entry.path();
            let dst_child = dst.join(entry.file_name());
            rename_cross_fs(&src_child, &dst_child)?;
        }
        std::fs::remove_dir(src)?;
    } else {
        std::fs::copy(src, dst)?;
        std::fs::remove_file(src)?;
    }
    Ok(())
}
